# Generated by Django 4.1.6 on 2023-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatar_profile/avatar.jpg', upload_to='images/avatar_profile'),
        ),
    ]
